spring:
  redis:
    host: 127.0.0.1
  application:
    #    注册到eureka中的名字
    name: zuul-server
server:
  servlet:
    #    根路径
    context-path: /
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: http://user:admin@127.0.0.1:8888/eureka
#路由网关
zuul:
  routes:
    authServer:
      path: /authToken/**
      service-id: auth-server
    daoServer:
      path: /daoServer/**
      service-id: dao-server
  ignored-services: "*"  #不能使用这个访问
  prefix: /tchmanage    #设置公共的前缀

